import {lines} from './mantra.js';
const $=id=>document.getElementById(id);
const player=document.querySelector('.player');
const audioBuffers=new Map(), audioLoads=new Map();
let timing,ctx,buffer,source,gain,origin=0,offset=0,clip=null,playing=false,waiting=false,request=0,repeatTimer=0,rate=1,pass=0,activeLine=-1,activeWord=-1,focusLine=-1,lastTouch=-10000,animation=0,hidden=false;
const rows=[],buttons=[];
const fmt=t=>`${Math.floor(Math.max(0,t)/60)}:${String(Math.floor(Math.max(0,t)%60)).padStart(2,'0')}`;
const say=message=>{$('status').textContent=message;};
function buildCard(){[lines.slice(0,44),lines.slice(44)].forEach((group,column)=>{const el=document.createElement('div');el.className='column';group.forEach((text,i)=>{const n=i+(column?44:0);const row=document.createElement('div');row.className='line';row.id=`line-${n+1}`;const num=document.createElement('button');num.type='button';num.className='line-number';num.textContent=n+1;num.setAttribute('aria-label',`Play line ${n+1}`);num.title=`Play line ${n+1}`;num.onclick=()=>playLine(n);const words=document.createElement('span');words.className='words';buttons[n]=text.split(' ').map((word,j)=>{const b=makeWord(word,n,j);words.append(b,document.createTextNode(' '));return b});row.append(num,words);rows[n]=row;el.append(row)});$('lines').append(el)})}
function makeWord(word,n,j){const b=document.createElement('button');b.type='button';b.className='word';b.textContent=word;b.setAttribute('aria-label',`Play ${word}, line ${n+1}, word ${j+1}`);b.title=`Hear “${word}” in line ${n+1}`;b.onclick=()=>playWord(n,j);return b}
function error(e){$('error').hidden=false;$('error').textContent='The recording could not play. Check your connection and try Play again, or use the Original recording link.';say('Audio unavailable. Try again.');console.warn('Audio playback unavailable:',e?.message||e)}
async function audioReady(speed){if(!ctx){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)throw new Error('Web Audio unavailable');ctx=new AudioContext()}await ctx.resume();if(audioBuffers.has(speed)){buffer=audioBuffers.get(speed);return buffer}if(!audioLoads.has(speed)){const file=speed===1?'recording.mp3':speed===0.8?'recording-080.mp3':'recording-065.mp3';audioLoads.set(speed,fetch('./'+file).then(r=>{if(!r.ok)throw new Error('Recording request failed');return r.arrayBuffer()}).then(data=>ctx.decodeAudioData(data)).then(b=>{audioBuffers.set(speed,b);return b}).catch(e=>{audioLoads.delete(speed);throw e}))}buffer=await audioLoads.get(speed);return buffer}
function position(){return playing?Math.min(clip?.end??timing.duration,offset+Math.max(0,ctx.currentTime-origin)*rate):offset}
function stopSound(){if(source){source.onended=null;try{source.stop()}catch{}source.disconnect();source=null}if(gain){gain.disconnect();gain=null}playing=false;cancelAnimationFrame(animation)}
function cancel(){++request;clearTimeout(repeatTimer);repeatTimer=0;waiting=false;offset=position();stopSound()}
function setState(state){player.dataset.state=state;$('play-icon').textContent=state==='playing'?'Ⅱ':state==='loading'?'…':'▶';$('play').setAttribute('aria-label',state==='playing'||state==='waiting'?'Pause playback':clip?.kind==='word'?`Replay word ${lines[clip.line].split(' ')[clip.word]}`:clip?.kind==='line'?`Replay line ${clip.line+1}`:'Play recording')}
function pause(){cancel();setState('paused');say('Paused');if(timing)render(offset)}
function selectClip(c){clip=c;rows.forEach(r=>r.classList.remove('selected-line'));buttons.flat().forEach(b=>b.classList.remove('selected-word'));if(c.line!=null){rows[c.line].classList.add('selected-line');if(c.word!=null)buttons[c.line][c.word].classList.add('selected-word');showFocus(c.line)}$('mode-label').textContent=c.kind==='full'?'LISTEN & FOLLOW':'LISTEN & REPEAT';$('selection-label').textContent=c.kind==='full'?'Whole recording':c.kind==='line'?`Line ${c.line+1} of 87`:`${lines[c.line].split(' ')[c.word]} · line ${c.line+1}`;$('whole').textContent=c.kind==='full'?'Play from beginning':'Play whole recording'}
async function start(c,at=c.start){cancel();const own=request;selectClip(c);offset=Math.max(c.start,Math.min(at,c.end));setState('loading');say('Preparing the recording…');$('error').hidden=true;try{const wantedRate=rate;const readyBuffer=await audioReady(wantedRate);if(own!==request||rate!==wantedRate)return;buffer=readyBuffer;startLoaded(c,offset)}catch(e){if(own===request){setState('paused');error(e)}}}
function startLoaded(c,at){stopSound();waiting=false;offset=Math.max(c.start,Math.min(at,c.end));if(c.end-offset<.025)offset=c.start;origin=ctx.currentTime+.015;source=ctx.createBufferSource();gain=ctx.createGain();source.buffer=audioBuffers.get(rate);source.playbackRate.value=1;source.connect(gain);gain.connect(ctx.destination);const duration=(c.end-offset)/rate;gain.gain.setValueAtTime(0,origin);gain.gain.linearRampToValueAtTime(1,origin+Math.min(.008,duration/4));gain.gain.setValueAtTime(1,origin+Math.max(.008,duration-.012));gain.gain.linearRampToValueAtTime(0,origin+duration);const own=request;source.onended=()=>{if(own!==request)return;offset=c.end;stopSound();render(Math.max(c.start,offset-.025));if($('repeat').checked){waiting=true;setState('waiting');say('Your turn — repeat aloud');repeatTimer=setTimeout(()=>{if(own!==request)return;start(c,c.start)},Number($('gap').value)*1000)}else{setState('paused');say(c.kind==='full'?'Recording complete':'Tap Play to hear it again')}};source.start(origin,offset/rate,(c.end-offset)/rate);playing=true;setState('playing');say(c.kind==='full'?'Follow the highlighted words':$('repeat').checked?'Listen, then repeat in the pause':'Listening');tick()}
function full(){if(!timing)return;start({kind:'full',start:0,end:timing.duration})}
function playLine(n){if(!timing)return;if(!Number.isInteger(n)||n<0||n>=lines.length)throw new Error('Choose a line from 1 to 87');const t=timing.passages[pass].lines[n];return start({kind:'line',line:n,start:t.start,end:t.end})}
function playWord(n,j){if(!timing)return;const words=lines[n]?.split(' ');if(!words||!Number.isInteger(j)||j<0||j>=words.length)throw new Error('Choose an existing word');const t=timing.passages[pass].lines[n].words[j];return start({kind:'word',line:n,word:j,start:t[0],end:t[1]})}
function toggle(){if(!timing)return;if(playing||waiting||player.dataset.state==='loading')return pause();if(!clip)return full();const at=offset>=clip.end-.03?clip.start:offset;start(clip,at)}
function showFocus(n){if(focusLine===n)return;focusLine=n;$('focus-number').textContent=`LINE ${n+1} OF 87`;$('focus-words').replaceChildren();lines[n].split(' ').forEach((w,j)=>$('focus-words').append(makeWord(w,n,j),document.createTextNode(' ')));$('previous').disabled=n===0;$('next').disabled=n===86}
function render(t){$('clock').innerHTML=`${fmt(t)} <span>/ ${fmt(timing.duration)}</span>`;$('seek').value=t;$('seek').setAttribute('aria-valuetext',`${fmt(t)} of ${fmt(timing.duration)}`);const p=timing.passages.findIndex((p,i)=>t>=p.start&&(i===timing.passages.length-1||t<timing.passages[i+1].start));if(p>=0&&p!==pass&&clip?.kind==='full'){pass=p;$('passage').value=String(p)}const ls=timing.passages[pass].lines;let ln=ls.findIndex((l,i)=>t>=l.start&&(i===ls.length-1?t<=l.end:t<ls[i+1].start));let w=ln<0?-1:ls[ln].words.findIndex(a=>t>=a[0]&&t<a[1]);if(clip?.kind==='word'){ln=clip.line;w=clip.word}else if(clip?.kind==='line'&&t>=clip.end-.03){ln=clip.line;w=ls[ln].words.length-1;}const changed=ln!==activeLine;if(changed){if(activeLine>=0)rows[activeLine].classList.remove('active-line');activeLine=ln;if(ln>=0){rows[ln].classList.add('active-line');showFocus(ln);if(playing&&$('follow').checked&&performance.now()-lastTouch>4000){const r=rows[ln].getBoundingClientRect(),bottom=player.getBoundingClientRect().bottom;if(r.top<bottom+15||r.bottom>window.innerHeight-30){window.scrollBy({top:r.top-bottom-Math.max(20,(window.innerHeight-bottom-r.height)/2),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}}}if(w!==activeWord||changed){document.querySelectorAll('.active-word').forEach(b=>b.classList.remove('active-word'));if(ln>=0&&w>=0){buttons[ln][w].classList.add('active-word');$('focus-words').querySelectorAll('.word')[w]?.classList.add('active-word')}activeWord=w}}
function tick(){if(!playing)return;render(Math.max(offset,position()));animation=requestAnimationFrame(tick)}
$('play').onclick=toggle;$('whole').onclick=full;
$('seek').oninput=()=>{$('clock').innerHTML=`${fmt(Number($('seek').value))} <span>/ ${fmt(timing?.duration||224)}</span>`};
$('seek').onchange=()=>{if(!timing)return;const at=Number($('seek').value);const wasPlaying=playing;cancel();selectClip({kind:'full',start:0,end:timing.duration});offset=at;render(at);if(wasPlaying)start(clip,at);else{setState('paused');say('Tap Play to continue from here')}};
$('speed').onchange=()=>{const at=position();rate=Number($('speed').value);if(playing||player.dataset.state==='loading')start(clip,at)};
$('passage').onchange=()=>{cancel();pass=Number($('passage').value);offset=timing.passages[pass].start;clip=null;selectClip({kind:'full',start:0,end:timing.duration});setState('paused');render(offset);say('Tap Play to begin this passage')};
$('repeat').onchange=()=>{$('gap-label').classList.toggle('inactive',!$('repeat').checked);if(waiting&&!$('repeat').checked){clearTimeout(repeatTimer);waiting=false;setState('paused');say('Repeat off')}else if(playing)say($('repeat').checked?'Listen, then repeat in the pause':'Listening')};
$('previous').onclick=()=>playLine(Math.max(0,(focusLine<0?1:focusLine)-1));$('next').onclick=()=>playLine(Math.min(86,focusLine+1));
$('hide').onclick=()=>{hidden=!hidden;$('hide').textContent=hidden?'Show words':'Hide words';$('hide').setAttribute('aria-pressed',String(hidden));$('lines').classList.toggle('concealed',hidden);$('focus-words').classList.toggle('concealed',hidden)};
window.addEventListener('wheel',()=>lastTouch=performance.now(),{passive:true});window.addEventListener('touchstart',()=>lastTouch=performance.now(),{passive:true});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){pause();return}if(e.code==='Space'&&!/INPUT|SELECT|BUTTON|TEXTAREA|SUMMARY/.test(e.target.tagName)){e.preventDefault();toggle()}});
window.addEventListener('pagehide',()=>cancel());
function readState(){return {state:player.dataset.state,position:Math.round(position()*100)/100,selection:clip?.kind||'full',line:clip?.line!=null?clip.line+1:null,word:clip?.word!=null?clip.word+1:null,passage:pass+1,repeat:$('repeat').checked,rate,highlightedLine:activeLine<0?null:activeLine+1,highlightedWord:activeWord<0?null:activeWord+1}}
function registerTools(){const mc=document.modelContext;if(!mc?.registerTool)return;const controller=new AbortController();const definitions=[{name:'get_practice_state',description:'Read the current playback, selected line or word, and highlight.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>readState()},{name:'play_mantra_line',description:'Play a numbered line of the Great Compassion mantra using the selected recorded passage.',inputSchema:{type:'object',properties:{line:{type:'integer',minimum:1,maximum:87}},required:['line'],additionalProperties:false},execute:async input=>{if(!Number.isInteger(input.line)||input.line<1||input.line>87)throw new Error('Line must be an integer from 1 to 87');await playLine(input.line-1);return readState()}},{name:'play_mantra_word',description:'Play one word in a numbered mantra line. Word numbering begins at 1.',inputSchema:{type:'object',properties:{line:{type:'integer',minimum:1,maximum:87},word:{type:'integer',minimum:1}},required:['line','word'],additionalProperties:false},execute:async input=>{if(!Number.isInteger(input.line)||input.line<1||input.line>87||!Number.isInteger(input.word)||input.word<1||input.word>lines[input.line-1].split(' ').length)throw new Error('Choose an existing line and word');await playWord(input.line-1,input.word-1);return readState()}},{name:'pause_mantra',description:'Pause playback and cancel any pending repeat.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{pause();return readState()}}];for(const d of definitions){try{Promise.resolve(mc.registerTool({...d,annotations:{readOnlyHint:false,untrustedContentHint:false,...d.annotations}},{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
buildCard();$('gap-label').classList.add('inactive');$('previous').disabled=true;
fetch('./timings.json').then(r=>{if(!r.ok)throw new Error('Timing map unavailable');return r.json()}).then(data=>{timing=data;$('seek').max=timing.duration;timing.passages.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.label||`Recitation ${i+1}`;$('passage').append(o)});$('play').disabled=false;say('Ready when you are');render(0);registerTools()}).catch(e=>{say('The timing map is unavailable. Please reload.');$('error').hidden=false;$('error').textContent='This practice page could not finish loading. Please reload the page.';console.warn(e)});
