export const lines = [
'Na Mwo He La Da Nwo Dwo La Ye Ye',
'Na Mwo E Li Ye',
'Pwo Lu Jye Di Shau Bwo La Ye',
'Pu Ti Sa Two Pe Ye',
'Mwo He Sa Two Pe Ye',
'Mwo He Jya Lu Ni Jya Ye',
'Nan',
'Sa Pan La Fa Ye',
'Swo Da Nwo Da Sye',
'Na Mwo Syi Ji Li Two Yi Meng E Li Ye',
'Pe Lu Ji Di Shr Fwo La Leng Two Pe',
'Na Mwo Nwo La Jin Chr',
'Syi Li Mwo He Pan Dwo Sa Mye',
'Sa Pe E Two Dou Shu Peng',
'E Shr Yun',
'Sa Pe Sa Dwo Na Mwo Pe Sa Dwo',
'Na Mwo Pe Chye',
'Mwo Fa Te Dou',
'Da Jr Two',
'Nan',
'E Pe Lu Syi',
'Lu Jya Di',
'Jya La Di',
'Yi Syi Li',
'Mwo He Pu Ti Sa Two',
'Sa Pe Sa Pe',
'Mwo La Mwo La',
'Mwo Syi Mwo Syi Li Two Yun',
'Jyu Lu Jyu Lu Jye Meng',
'Du Lu Du Lu Fa She Ye Di',
'Mwo He Fa She Ye Di',
'Two La Two La',
'Di Li Ni',
'Shr Fwo La Ye',
'Je La Je La',
'Mwo Mwo Fa Mwo La',
'Mu Di Li',
'Yi Syi Yi Syi',
'Shr Nwo Shr Nwo',
'E La Shen Fwo La She Li',
'Fa Sha Fa Shen',
'Fwo La She Ye',
'Hu Lu Hu Lu Mwo La',
'Hu Lu Hu Lu Syi Li',
'Swo La Swo La',
'Syi Li Syi Li',
'Su Lu Su Lu',
'Pu Ti Ye Pu Ti Ye',
'Pu Two Ye Pu Two Ye',
'Mi Di Li Ye',
'Nwo La Jin Chr',
'Di Li Shai Ni Nwo',
'Pe Ye Mwo Nwo',
'Swo Pe He',
'Syi Two Ye',
'Swo Pe He',
'Mwo He Syi Two Ye',
'Swo Pe He',
'Syi Two Yu Yi',
'Shr Pan La Ye',
'Swo Pe He',
'Nwo La Jin Chr',
'Swo Pe He',
'Mwo La Nwo La',
'Swo Pe He',
'Syi Lu Seng E Mu Chywe Ye',
'Swo Pe He',
'Swo Pe Mwo He E Syi Two Ye',
'Swo Pe He',
'Je Ji La E Syi Two Ye',
'Swo Pe He',
'Bwo Two Mwo Jye Syi Two Ye',
'Swo Pe He',
'Nwo La Jin Chr Pan Chye La Ye',
'Swo Pe He',
'Mwo Pe Li Sheng Jye La Ye',
'Swo Pe He',
'Na Mwo He La Da Nwo Dwo La Ye Ye',
'Na Mwo E Li Ye',
'Pwo Lu Jye Di',
'Shau Pan La Ye',
'Swo Pe He',
'Nan',
'Syi Dyan Du',
'Man Dwo La',
'Ba Two Ye',
'Swo Pe He'
];
